apiVersion: v1
kind: Service
metadata:
  name: my-nginx1
  labels:
    run: my-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 8090
    protocol: TCP
    name: http
  selector:
    app: temp-nginx
